### ISSUE TITLE
Global definition of sources

### ISSUE THREAD

**Issue by jrschumacher** [sahusoftcom/plupload-angular-directive#1]
It would be nice if there was a way to set these globally through the modal config or the like.

https://github.com/sahusoftcom/plupload-angular-directive/blob/master/src/js/plupload-angular-directive.js#L40-L43

**Comment by ektatechila** [comment]
Hi,

I am trying to set the upload URL through controller of the page, as per the requirement the upload url will be dynamic. I assigned the url value to the $scope like 
$scope.uploadUrl=someVariable

and then tried to use it like

pl-url="uploadURL"

but its not able to assign the dynamic url value somehow can you please suggest some way by which I can do it.

**Comment by saurabhsahu13** [comment]
Hi,

pl-url attribute takes string as an input. So, you must use
pl-url="{{uploadUrl}}" to use the url from a scope variable.

Thanks.
