### ISSUE TITLE
onFileError is not defined

### ISSUE THREAD

**Issue by brunogonncalves** [sahusoftcom/plupload-angular-directive#15]
Have a bug "Uncaught ReferenceError: onFileError is not defined", but my attribute on-file-error="handleError()" are ben defined in my scope, i will do a pull request for correct it ok ?

**Comment by sanketsahusoft** [comment]
If you fix it then do send a pull request. I am not getting enough time to maintain this.

I find this jQuery file upload a good alternative.
https://blueimp.github.io/jQuery-File-Upload/angularjs.html

**Comment by codeconsole** [comment]
Are you recommending using jQuery File upload over plupload?

**Comment by sanketsahusoft** [comment]
Yes, they (jQuery File upload) have a very nice AngularJS directive and it is better maintained than this repo.

**Comment by sanketsahusoft** [comment]
@codeconsole Fixed this issue which is merged to master now.

**Comment by codeconsole** [comment]
I care more about the underlying api than the directive.  Without angular, do you think jQuery file upload is better than plupload?

**Comment by brunogonncalves** [comment]
jQuery file upload is complex, I really don't like that. Have no good patters for angular, for me, jQuery file upload is not a good
