### ISSUE TITLE
We need more atention for updates

### ISSUE THREAD

**Issue by brunogonncalves** [sahusoftcom/plupload-angular-directive#18]
Hi, can you add me like a admin contributor ?  I use this directive for all projects in my work, and I see that it need many updates and features, during my work i can help to increase features and resolve issues.
 You recommended for we use [jQuery File Upload](https://github.com/blueimp/jQuery-File-Upload), but it is not a good plugin, i don't enjoyed because is not a simple, and have a bad code for angular. Please consider this.

**Comment by epicleptico** [comment]
I am with @brunogonncalves.

 I use this directive as base directive for a domain oriented directive in my projects. I can activelly support and resolve issues in this simple directive.

If you cannot manage and don't want to give admin away, we can just make a fork

**Comment by sanketsahusoft** [comment]
Sorry guys, I am here to help. Send in your pull requests. I will try to be more active and maintain this.

**Comment by rvanbaalen** [comment]
@brunogonncalves and @epicleptico why not throw some PR's at it instead of requesting admin rights?

**Comment by sanketsahusoft** [comment]
@rvanbaalen It was because, I wasn't active enough to maintain this repo and had many pending PRs. Though, I am trying to be responsible and merging PRs now. Just in case if I fail to do so, I would share the admin rights in future, not now.
