### ISSUE TITLE
Setting http headers in plupload options?

### ISSUE THREAD

**Issue by stefanhuber** [sahusoftcom/plupload-angular-directive#31]
Is it possible to set the headers option for the plupload? Otherwise i see no possibility to set authentication headers...

**Comment by epicleptico** [comment]
just use *plMultiParamsModel* attribute for achieve that (is an object)

**Comment by sanketsahusoft** [comment]
`pl-multi-params` can be used for parameters.

OR

The `pl-instance` attribute on the element populates the plupload object in the scope. That plupload instance can be used to set the headers or anything.

**Comment by stefanhuber** [comment]
thx, i oversaw it... (also here: https://github.com/sahusoftcom/plupload-angular-directive/blob/master/src/js/plupload-angular-directive.js#L105)
