### ISSUE TITLE
Is there any change-log for this directive.

### ISSUE THREAD

**Issue by zunairzubair** [sahusoftcom/plupload-angular-directive#33]
Hey, I used a previous version of this directive in one of my projects. Now I intend to upgrade it to the latest version but having some issues in some features. Like the on-upload-finish event is not registering callbacks.
So is there a change-log kind of document where I can see what update fixed issues or added some new functionality.
Thanks.

**Comment by sanketsahusoft** [comment]
Sorry, we don't have anything like change-log but there haven't been a lot of changes, you can check the commit and merge logs.
