### ISSUE TITLE
Not able to dynamically change the url to which the image is uploaded.

### ISSUE THREAD

**Issue by shyamsathyanathan** [sahusoftcom/plupload-angular-directive#43]
I am using the pl-url directive to change the url to which the image gets uploaded but no matter what, once the form is submitted, the POST request goes to /upload.php rather than the url I have overriden. I have already posted a question on StackOverflow regarding this, but no answers have come up so far: http://stackoverflow.com/questions/34239553/how-to-set-dynamic-url-in-pluoplad-angular-directive.

This might be a trivial issue, but I don't see the docs helping me to fix this.

**Comment by sanketsahusoft** [comment]
Sorry, but nobody is maintaining the repo anymore in support of Angular jQuery Fileupload and other better available scripts.
